client_hostname: auradar-eeeeeeee
POINT_CLOUD2: true
MESSAGE_NUMBER: 2
radars:
  0dd98aa5: RADAR_FRONT
  564d6b80: RADAR_FRONT_RIGHT
  2812b707: RADAR_REAR_RIGHT
  2f7e83f9: RADAR_REAR_LEFT
  2d12af50: RADAR_FRONT_LEFT