client_hostname: auradar-eeeeeeee
POINT_CLOUD2: true
radars:
  9c281337: RADAR FRONT
  05d9f6e4: RADAR FRONT RIGHT
  5ff85500: RADAR REAR RIGHT
  c0a4ab10: RADAR REAR LEFT
  610ddb0e: RADAR FRONT LEFT