client_hostname: auradar-eeeeeeee
POINT_CLOUD2: true
MESSAGE_NUMBER: 2
radars:
  24acac67: # 156
    frame_id: RADAR_FRONT
    xyz: [0, 0.2332, 0.06]
    rpy: [0, 0, -90]
  8d26618b: # 167
    frame_id: RADAR_FRONT_RIGHT
    xyz: [0.2028, 0.1175, 0.06]
    rpy: [0, 0, -190]
  402780a0: # 168
    frame_id: RADAR_REAR_RIGHT
    xyz: [0.1532, -0.1908, 0.06]
    rpy: [0, 0, 110]
  e2aee171: # 169
    frame_id: RADAR_REAR_LEFT # 180 rotation based on y axis
    xyz: [-0.1532, -0.1908, 0.06]
    rpy: [0, 180, 70]
  716d8053: # 165
    frame_id: RADAR_FRONT_LEFT
    xyz: [-0.2028, 0.1175, 0.06]
    rpy: [0, 0, 10]


