client_hostname: auradar-eeeeeeee
POINT_CLOUD2: true
radars:
  0dd98aa5: RADAR_FRONT
  2812b707: RADAR_FRONT_RIGHT
  2d12af50: RADAR_REAR_RIGHT
  564d6b80: RADAR_REAR_LEFT
  2f7e83f9: RADAR_FRONT_LEFT