client_hostname: auradar-eeeeeeee
POINT_CLOUD2: true
radars:
  0dd98aa5: RADAR FRONT
  2812b707: RADAR FRONT RIGHT
  2d12af50: RADAR REAR RIGHT
  564d6b80: RADAR REAR LEFT
  2f7e83f9: RADAR FRONT LEFT
  27c06058: RADAR
  db089dfa: RADAR
  916b3915: RADAR
  273196c2: RADAR
  3207df55: RADAR